import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "LendyWendy terms of service - rules and guidelines for using our mortgage matching platform.",
  alternates: { canonical: "https://lendywendy.com/terms" },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="container mx-auto px-4 py-16 max-w-3xl">
        <h1 className="text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-10">Last updated: March 2, 2026</p>

        <div className="prose prose-gray max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mt-0">1. Acceptance of Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              By accessing and using lendywendy.com (the &quot;Service&quot;), you accept and agree to be bound
              by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">2. Description of Service</h2>
            <p className="text-gray-600 leading-relaxed">
              LendyWendy is a free mortgage matching platform that connects borrowers with licensed
              mortgage professionals and lenders in California. <strong>LendyWendy is not a lender,
              broker, or financial advisor.</strong> We do not make loans, offer interest rates, or
              provide financial advice. All loan applications are subject to lender approval and underwriting.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">3. Not Financial Advice</h2>
            <p className="text-gray-600 leading-relaxed">
              The information provided through our Service, including our AI Mortgage Advisor and
              Mortgage Readiness Score, is for informational and educational purposes only. It does
              not constitute financial, legal, or tax advice. You should consult with qualified
              professionals before making any financial decisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">4. AI Advisor Disclaimer</h2>
            <p className="text-gray-600 leading-relaxed">
              Our AI Mortgage Advisor provides general information about mortgage products and the
              lending process. Responses are generated by artificial intelligence and may not always
              be accurate or complete. The AI advisor does not have access to real-time interest rates,
              your actual credit report, or lender-specific criteria. Any information provided should
              be verified with a licensed mortgage professional.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">5. Mortgage Readiness Score</h2>
            <p className="text-gray-600 leading-relaxed">
              The Mortgage Readiness Score is an educational tool based on self-reported information.
              It is not a credit score, pre-approval, or guarantee of loan qualification. Your actual
              qualification will depend on verified financial information reviewed by a lender.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">6. User Responsibilities</h2>
            <p className="text-gray-600 leading-relaxed">You agree to:</p>
            <ul className="list-disc pl-6 text-gray-600 space-y-1">
              <li>Provide accurate and truthful information</li>
              <li>Not use the Service for any unlawful purpose</li>
              <li>Not attempt to gain unauthorized access to our systems</li>
              <li>Not interfere with or disrupt the Service</li>
              <li>Not use automated tools to scrape or collect data from the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">7. Compensation Disclosure</h2>
            <p className="text-gray-600 leading-relaxed">
              LendyWendy may receive compensation from mortgage lenders and professionals when
              you are matched and subsequently obtain a loan. This compensation does not increase
              your costs and does not influence which lender or professional is recommended to you.
              Matching is based on your specific needs, location, and loan type.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">8. Equal Housing Opportunity</h2>
            <p className="text-gray-600 leading-relaxed">
              LendyWendy and our partner lenders are committed to Equal Housing Opportunity.
              We do not discriminate on the basis of race, color, religion, national origin, sex,
              familial status, disability, or any other protected class under federal, state, or
              local law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">9. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed">
              LendyWendy is provided &quot;as is&quot; without warranty of any kind. We are not liable for
              any damages arising from your use of the Service, the accuracy of information provided
              by our AI advisor, or the actions of matched mortgage professionals or lenders.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">10. Privacy</h2>
            <p className="text-gray-600 leading-relaxed">
              Your use of the Service is also governed by our{" "}
              <Link href="/privacy-policy" className="text-teal-600 hover:underline">
                Privacy Policy
              </Link>
              , which describes how we collect, use, and protect your information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">11. Changes to Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              We reserve the right to modify these Terms at any time. Changes are effective
              immediately upon posting to this page. Your continued use of the Service after
              changes constitutes acceptance of the modified terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">12. Governing Law</h2>
            <p className="text-gray-600 leading-relaxed">
              These Terms are governed by the laws of the State of California, without regard
              to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900">13. Contact Us</h2>
            <p className="text-gray-600 leading-relaxed">
              If you have any questions about these Terms, please contact us at{" "}
              <a href="mailto:legal@lendywendy.com" className="text-teal-600 hover:underline">
                legal@lendywendy.com
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-200">
          <Link href="/" className="text-teal-600 hover:underline font-medium">
            &larr; Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
